---
# This playbook tests the script module on Windows hosts

- name: Run cypher script reference
  hosts: all 
  gather_facts: false
  tasks:
    - name: Run cypher write
      script: "echo {{ lookup('hashi_vault', 'secret=password/rando:value url=http://localhost:8080/api/cypher/v1 token')}}"
